### ISSUE TITLE
It is suggested to add star rating algorithm

### ISSUE THREAD

**Issue by planet-23** [ppy/osu-wiki#8779] opened 2023-02-10 10:11 UTC
I hope to add various modes of difficulty algorithms to help people who need or are interested to understand the specific algorithms.

**Comment by Walavouchey** [comment] 2023-02-10 10:48
duplicate of https://github.com/ppy/osu-wiki/issues/2701.

if you or anyone else feels like they can read lazer's source code and explain the algorithms involved in a clear way along with diagrams ([`meta/osu-matplotlib-theme`](https://github.com/ppy/osu-wiki/tree/master/meta/osu-matplotlib-theme) can help you with that), do tell us.

**Closed by Walavouchey** 2023-02-10 10:48 UTC

**Comment by planet-23** [comment] 2023-02-13 02:02
Thanks for your reply. I'm not C# developer,but i try my best to read it.(Although I don't think I can do it)
