### ISSUE TITLE
Clean up articles about score multipliers

### ISSUE THREAD

**Issue by Sunnyboy971** [ppy/osu-wiki#8936] opened 2023-03-12 10:37 UTC
Now we have got the definitions of the combo multiplier, difficulty multiplier and the mod multiplier from `Gameplay/Score/ScoreV1/osu!`, which also gives the detailed correct formula. 
In my perspective, the "score multiplier" should refer to **the overall definition** of the three multipliers. The existing `Gameplay/Game_modifier/Score_multiplier` should refer to **the mod multiplier**.
At present this article causes some misunderstanding like #4448 . Maybe we just need to put these definition articles under the same category `Score Multipliers`, write a glossary for it and rewrite existing articles accordingly.

Todo:
- [x] #8958

**Comment by TicClick** [comment] 2023-05-10 21:19
apart from https://github.com/ppy/osu-wiki/issues/4448, I don't see any misunderstandings, and the plan from https://github.com/ppy/osu-wiki/pull/8958 was chopped down, so the rest of the issue isn't really happening

what would be your other ideas? if there aren't any, I'd rather close the issue instead.

**Comment by Sunnyboy971** [comment] 2023-05-11 00:55
OK I think that's all

**Closed** 2023-05-11 00:55 UTC
