### ISSUE TITLE
beatmap lag

### ISSUE THREAD

**Issue by Wei1710** [ppy/osu-wiki#10765] opened 2024-01-06 22:59 UTC
on some beatmaps, the first object / note, circle lag, so i can't read the approach circle it stop because of lag but only for first object for each beatmap, i tested with mouse and also with tablet. it lags out for 1 second and then everything is normal but that 1 second make me never be able to perfect hit on first circle

**Comment by Hiviexd** [comment] 2024-01-06 23:13
1. this is the [osu! wiki](https://osu.ppy.sh/wiki) repository, not the one for the game client.
2. your issue is most likely a duplicate of https://github.com/ppy/osu-stable-issues/issues/1090, I suggest reading the reply there for a proper response on this.

**Closed by Hiviexd** 2024-01-06 23:13 UTC
